 #
 # This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 # This class includes values of some nesC constants from
 # ../RssiRanging.h.
 #/

NUM_NODES = 5

class Constants:
    SEND_BEACON_MS = 250
    RSSIMSG_PORT = 7010
    SEND_REPORT_MS = 1000
    UNDEF_RSSI = 127
    REPORTMSG_PORT = 7011

