#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'ReportMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 6

# The Active Message type associated with this message.
AM_TYPE = -1

class ReportMsg(tinyos.message.Message.Message):
    # Create a new ReportMsg of size 6.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=6):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <ReportMsg> \n"
        try:
            s += "  [id=0x%x]\n" % (self.get_id())
        except:
            pass
        try:
            s += "  [rssi=";
            for i in range(0, 5):
                s += "0x%x " % (self.getElement_rssi(i) & 0xff)
            s += "]\n";
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: id
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 8
    #

    #
    # Return whether the field 'id' is signed (False).
    #
    def isSigned_id(self):
        return False
    
    #
    # Return whether the field 'id' is an array (False).
    #
    def isArray_id(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'id'
    #
    def offset_id(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'id'
    #
    def offsetBits_id(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'id'
    #
    def get_id(self):
        return self.getUIntElement(self.offsetBits_id(), 8, 1)
    
    #
    # Set the value of the field 'id'
    #
    def set_id(self, value):
        self.setUIntElement(self.offsetBits_id(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'id'
    #
    def size_id(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'id'
    #
    def sizeBits_id(self):
        return 8
    
    #
    # Accessor methods for field: rssi
    #   Field type: byte[]
    #   Offset (bits): 8
    #   Size of each element (bits): 8
    #

    #
    # Return whether the field 'rssi' is signed (False).
    #
    def isSigned_rssi(self):
        return False
    
    #
    # Return whether the field 'rssi' is an array (True).
    #
    def isArray_rssi(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'rssi'
    #
    def offset_rssi(self, index1):
        offset = 8
        if index1 < 0 or index1 >= 5:
            raise IndexError
        offset += 0 + index1 * 8
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'rssi'
    #
    def offsetBits_rssi(self, index1):
        offset = 8
        if index1 < 0 or index1 >= 5:
            raise IndexError
        offset += 0 + index1 * 8
        return offset
    
    #
    # Return the entire array 'rssi' as a byte[]
    #
    def get_rssi(self):
        tmp = [None]*5
        for index0 in range (0, self.numElements_rssi(0)):
                tmp[index0] = self.getElement_rssi(index0)
        return tmp
    
    #
    # Set the contents of the array 'rssi' from the given byte[]
    #
    def set_rssi(self, value):
        for index0 in range(0, len(value)):
            self.setElement_rssi(index0, value[index0])

    #
    # Return an element (as a byte) of the array 'rssi'
    #
    def getElement_rssi(self, index1):
        return self.getSIntElement(self.offsetBits_rssi(index1), 8, 1)
    
    #
    # Set an element of the array 'rssi'
    #
    def setElement_rssi(self, index1, value):
        self.setSIntElement(self.offsetBits_rssi(index1), 8, value, 1)
    
    #
    # Return the total size, in bytes, of the array 'rssi'
    #
    def totalSize_rssi(self):
        return (40 / 8)
    
    #
    # Return the total size, in bits, of the array 'rssi'
    #
    def totalSizeBits_rssi(self):
        return 40
    
    #
    # Return the size, in bytes, of each element of the array 'rssi'
    #
    def elementSize_rssi(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'rssi'
    #
    def elementSizeBits_rssi(self):
        return 8
    
    #
    # Return the number of dimensions in the array 'rssi'
    #
    def numDimensions_rssi(self):
        return 1
    
    #
    # Return the number of elements in the array 'rssi'
    #
    def numElements_rssi():
        return 5
    
    #
    # Return the number of elements in the array 'rssi'
    # for the given dimension.
    #
    def numElements_rssi(self, dimension):
        array_dims = [ 5,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
    #
    # Fill in the array 'rssi' with a String
    #
    def setString_rssi(self, s):
         l = len(s)
         for i in range(0, l):
             self.setElement_rssi(i, ord(s[i]));
         self.setElement_rssi(l, 0) #null terminate
    
    #
    # Read the array 'rssi' as a String
    #
    def getString_rssi(self):
        carr = "";
        for i in range(0, 4000):
            if self.getElement_rssi(i) == chr(0):
                break
            carr += self.getElement_rssi(i)
        return carr
    
